[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 0.95 # Slight transparency for aesthetics
decorations_theme_variant = "Dark"
startup_mode = "Maximized" # Open maximized by default


[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#282A36"  # Dracula background
foreground = "#F8F8F2"  # Dracula foreground

[colors.normal]
black = "#21222C"       # Dracula black
red = "#FF5555"         # Dracula red
green = "#50FA7B"       # Dracula green
yellow = "#F1FA8C"      # Dracula yellow
blue = "#BD93F9"        # Dracula blue
magenta = "#FF79C6"     # Dracula magenta
cyan = "#8BE9FD"        # Dracula cyan
white = "#F8F8F2"       # Dracula white

[colors.bright]
black = "#6272A4"       # Bright black (gray)
red = "#FF6E6E"         # Bright red
green = "#69FF94"       # Bright green
yellow = "#FFFFA5"      # Bright yellow
blue = "#D6ACFF"        # Bright blue
magenta = "#FF92DF"     # Bright magenta
cyan = "#A4FFFF"        # Bright cyan
white = "#FFFFFF"       # Bright white

[colors.selection]
background = "#383A46"  # Semi-transparent selection
text = "#FFFFFF"  # Selection text color

[font]
size = 14

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"           # Classic block cursor for better visibility
vi_mode_style = "Beam"    # Beam cursor in vi mode
unfocused_hollow = true
thickness = 0.2           # Slightly thicker for better visibility

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "DecreaseFontSize"

[general]
live_config_reload = true
working_directory = "None"

[terminal]
shell = "/bin/zsh -l"
